### ISSUE TITLE
stw.sorinsurance.org

### ISSUE THREAD

**Issue by GalacticNetwork** [sparkdns/registry#14]
### Domain

stw.sorinsurance.org

### Record type

CNAME

### Record value

stw.chickenkiller.com

### Record name

STW

### Does your record need a TXT record as well?

replit-verify=6648ea34-a7c9-4445-81ac-e81e313c94fc

### Code of Conduct

- [X] I agree to follow the Registry agreements

**Comment by proudparrot2** [comment]
Added!
